"""criando tabela de agendamentos

Revision ID: 480d10e4fb5c
Revises: d077872e7435
Create Date: 2026-07-20 20:47:58.132694

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "480d10e4fb5c"
down_revision = "d077872e7435"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient", sa.String(length=100), nullable=False),
        sa.Column("cpf", sa.String(length=14), nullable=False),
        sa.Column("doctor", sa.String(length=100), nullable=False),
        sa.Column("specialty", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedules_cpf"), ["cpf"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedules_cpf"))

    op.drop_table("schedules")
    # ### end Alembic commands ###
