"""adicionando convênio e status no schedule

Revision ID: 64b9275a4a42
Revises: 480d10e4fb5c
Create Date: 2026-07-21 15:58:12.234950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b9275a4a42'
down_revision = '480d10e4fb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('insurance')

    # ### end Alembic commands ###
